### ISSUE TITLE
Training code for the keypoint head?

### ISSUE THREAD

**Issue by AustrianOakvn** [sair-lab/SeqACE#4]
Hi, thank you for the great work, from your paper I understand that you pretrained the keypoint head supervised using keypoint from Superpoint and Scannet. I don't see training code for that part in the repo, can you provide it?

**Comment by xukuanHIT** [comment]
Hi, this repository only contains the [inference code](https://github.com/sair-lab/SeqACE/blob/28dd8bdbf31a2e2ceca85f8fd6d15bb5fcab31c8/ace_network.py#L182) and [trained model](https://github.com/sair-lab/SeqACE/blob/master/point_header.pt) of the keypoint head. The code for training the keypoint head is in another repository and we will consider releasing it after the paper is accepted.

**Comment by AustrianOakvn** [comment]
Thank you, good luck on your paper.
